source 'https://rubygems.org'

gem "test-unit",        "~> 3.1"
gem "rake",             "~> 10.4.2"
gem "rspec",            "~> 1.2.9"
gem "diff-lcs",         "~> 1.1.2"
gem "rack",             "~> 1.5.2"
gem "nokogiri",         "~> 1.6"
gem "merb-core",        "~> 1.1.3"
gem "selenium-client",  "~> 1.2.17"
gem "mechanize",        "~> 2.7.3"
gem "rails",            "~> 4.0.13"
gem "launchy",          "~> 2.0.2"
gem "rack-test",        "~> 0.6.2"
gem "sinatra",          "~> 1.4"
gem "thin",             "~> 1.6"
gem "byebug"
